project_name: rand-beer

before:
  hooks:
    - go mod tidy

builds:
  - id: 'rand-beer'
    main: ./
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
    ldflags:
      - '-s'
      - '-w'
      - '-X main.version={{ .Version }}'
      - '-X main.osArch={{ .Os }}/{{ .Arch }}'

archives:
  - id: "rand-beer"
    replacements:
      darwin: osx
      386: i386
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*

chocolateys:
  - name: 'rand-beer'
    authors: faabiosr
    project_url: https://github.com/faabiosr/rand-beer
    copyright: 2022 Fabio Ribeiro
    license_url: https://github.com/faabiosr/rand-beer/blob/main/LICENSE
    tags: "beer random names"
    summary: Generates random beer names
    description: |
      {{ .ProjectName }} generates random beer names every time that you run.

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
