name: test

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: unshallow
        run: git fetch --prune --unshallow

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'

      - name: run goreleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --snapshot --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
